ALTER TABLE media
  ADD COLUMN exif_stripped TINYINT NOT NULL DEFAULT 1,
  ADD COLUMN exif_has_gps TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN exif_has_device TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN exif_checked_at DATETIME NULL;
